### ISSUE TITLE
Cannot find module '../logger'

### ISSUE THREAD

**Issue by jorisw** [stockmlbot/DataSynchronizer#3]
I cannot get this project to run. If I'm doing the wrong thing, perhaps the docs could be updated to show how the project is supposed to be run?

I've completed all the installation steps without errors.

```
~/DataSynchronizer$ tsc --version
Version 3.3.3333

~/DataSynchronizer$ node --version
v10.15.2

~/DataSynchronizer$ npm run build
> tsc

~/DataSynchronizer$ npm run start
> cryptocurrency-exchange-data-synchronizer@3.0.0 start ~/DataSynchronizer
> node --experimental-worker --inspect=5858 -r ts-node/register ./src/index.ts

Debugger listening on ws://127.0.0.1:5858/3bb46e31-388a-47ee-aade-39fcd144693f
For help, see: https://nodejs.org/en/docs/inspector
info: StockML Synchronizer started
info: Livefeed API started
info: Startup finished
error: Worker error with exit code: Cannot find module '../logger' {"code":"MODULE_NOT_FOUND","stack":"Error: Cannot find module '../logger'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:507:25)\n    at Module.require (internal/modules/cjs/loader.js:637:17)\n    at require (internal/modules/cjs/helpers.js:22:18)\n    at Object.<anonymous> (~/DataSynchronizer/src/workers/worker.js:6:20)\n    at Module._compile (internal/modules/cjs/loader.js:689:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)\n    at Module.load (internal/modules/cjs/loader.js:599:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:530:3)"}
error: Worker stopped with exit code: 
```

**Comment by valamidev** [comment]
node --version
v10.15.2

Use Node v12+ , because we are using multi-threading for some background process.
