### ISSUE TITLE
(Non-fatal) 'tierBased' cannot be null

### ISSUE THREAD

**Issue by jorisw** [stockmlbot/DataSynchronizer#4]
I get a few of these while running the synchronizer:

I've followed the installation SQL scripts in `SQL/`.

Running MySQL 5.7.27.

```
error: ErrorColumn 'tierBased' cannot be null {"code":"ER_BAD_NULL_ERROR","errno":1048,"sqlState":"23000","sqlMessage":"Column 'tierBased' cannot be null","stack":"Error: Column 'tierBased' cannot be null\n    at PromisePool.query (DataSynchronizer/node_modules/mysql2/promise.js:330:22)\n    at MarketDataClass.market_data_replace (DataSynchronizer/src/marketdata/index.ts:112:20)\n    at MarketDataClass.update_market_data (DataSynchronizer/src/marketdata/index.ts:67:22)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
```

**Comment by valamidev** [comment]
Fixed, in 

https://github.com/stockmlbot/DataSynchronizer/commit/ca8481a0205062d220a74b995c95b2ebfd9134ad
